name: Angular + .NET CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  angular-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sampleapplication.client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build

  dotnet-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./SampleApplication.slnx

      - name: Build
        run: dotnet build ./SampleApplication.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test ./SampleApplication.slnx --configuration Release --no-build
